use_frameworks!

platform :ios, '8.0'

target 'WFullscreenPopGesture_Example' do
  pod 'WFullscreenPopGesture', :path => '../'

  target 'WFullscreenPopGesture_Tests' do
    inherit! :search_paths

    
  end
end
